### ISSUE TITLE
The "simonpi" script ends with "tcg fatal error" 

### ISSUE THREAD

**Issue by 3PO** [M0Rf30/simonpi#1]
Hi,

the "simonpi" script doesn't work on my system: 

Issue: https://paste.pound-python.org/show/KFiEchVd3tk2fjGiI5MU/

I'm using gentoo:

    server01 ~ # uname -a
    Linux server01 4.14.14-gentoo #1 SMP PREEMPT Sun Jan 21 09:32:19 CET 2018 x86_64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz GenuineIntel GNU/Linux
    server01 ~ #

Any suggestions?

**Comment by M0Rf30** [comment]
I've always used 2.11 version of qemu and never encountered this error. It should be a qemu error on dynamic code used for emulation. Try to update your version. Otherwise I could update kernels shipped with simonpi

**Comment by 3PO** [comment]
2.11 isn't in portage yet: https://packages.gentoo.org/packages/app-emulation/qemu

**Comment by M0Rf30** [comment]
Setting the PV variable to 9999 should compile the git version with no significant effort  or am I wrong?

**Comment by 3PO** [comment]
Yes you're right,  but don't want install the git version, because i have a working installation with some VMs and i don't want to destroy this.

**Comment by M0Rf30** [comment]
If you want you can try simonpi docker image.
Follow these instructions:
[How to run simonpi in a Docker container](https://github.com/M0Rf30/simonpi/blob/master/docker/README.md)
