### ISSUE TITLE
Hi I have been trying to set up Pi-hole, but I guess the dnsmasq port is already in use, what config do I need to change to make it work?

### ISSUE THREAD

**Issue by rdtor** [M0Rf30/simonpi#10]

**Comment by M0Rf30** [comment]
You can override 
GUESTPORT0
EXTERPORT0
GUESTPORT1
EXTERPORT1
variables to map a pi-hole instance installed on a vm.
simply by running EXTPORT=5353 GUESTPORT=53 simonpi rpi-X -r
and mixing it with a properly configure instance of pi-hole inside the vm
