### ISSUE TITLE
Enable networking

### ISSUE THREAD

**Issue by amo13** [M0Rf30/simonpi#13]
It's me again having some trouble... (using virtual machines for the first time)

How can I get the virtual rpi connected to the internet? I can boot into archlinuxarm for rpi4 but without networking it feels like I am locked in ;)
Is there a simple trick to use the host network interface in the virtual machine?

**Comment by M0Rf30** [comment]
Ok at first some considerations:
* a bridge and tun-tap device are created, binded with your physical connected network interface
* a dnsmasq instance is executed in order to provide a dns resolution for all the virtual simonpi machines.
vm should be automatically enable to the Internet. Check for port 53, before the execution of simonpi, otherwise you can check the docker images on docker hub

**Comment by amo13** [comment]
Thank you for the considerations.

I am a bit confused, because to me it looks like it could/should be working, but a `ping www.google.de` just returns `Name or service not known`, so apparently there is no DNS available. 

I did a `ip address` on the host machine and I get this:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 68:f7:28:f3:b7:f2 brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 5c:e0:c5:33:08:65 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.93/24 brd 192.168.178.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 860778sec preferred_lft 860778sec
    inet6 2003:c1:8f04:1700:ac2e:96d2:3d5a:8411/64 scope global dynamic noprefixroute 
       valid_lft 6764sec preferred_lft 719sec
    inet6 fe80::ec4d:db6e:f88:3600/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
5: wwp0s20u4i6: <BROADCAST,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 6a:b4:7e:e5:ee:ac brd ff:ff:ff:ff:ff:ff
6: rasp-br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ae:d9:46:9f:87:83 brd ff:ff:ff:ff:ff:ff
    inet 192.168.66.1/24 brd 192.168.66.255 scope global rasp-br0
       valid_lft forever preferred_lft forever
    inet6 fe80::acd9:46ff:fe9f:8783/64 scope link 
       valid_lft forever preferred_lft forever
7: rasp-tap0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel master rasp-br0 state UP group default qlen 1000
    link/ether 12:9a:d6:de:b1:31 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::109a:d6ff:fede:b131/64 scope link 
       valid_lft forever preferred_lft forever
```

`ip address` on the guest virtual machine gives only
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:c3:53:93:d5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:c3ff:fe53:93d5/64 scope link 
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```
Any clue how to get the guest connected to the internet?

**Comment by amo13** [comment]
I solved the problem by doing the following:
* Open Virtual Machine Manager (GUI)
* Edit > Connection Details
* Virtual Networks Tab > Start network (play button)

Afterwards, I can boot the Raspberry Pi virtual machine with `simonpi rpi-4 -r` and have a working internet connection. 

Maybe this solution can help other people new to virtual machines.
