### ISSUE TITLE
default   password for root (arch linux arm) user is ?

### ISSUE THREAD

**Issue by saxon17** [M0Rf30/simonpi#5]
alarm cant  config ip address
[alarm@alarmpi ~]$ ifconfig eth0 192.1.1.100
SIOCSIFADDR: Operation not permitted
SIOCSIFFLAGS: Operation not permitted

anyway how can i  reset the ip?

**Comment by M0Rf30** [comment]
Please try with dhcpcd eth0 command

**Comment by M0Rf30** [comment]
As said in alarm docs:
alarm:alarm
root:root

**Comment by saxon17** [comment]
sorry.   faild in vps

[root@alarmpi alarm]# dhcpcd eth0
DUID 00:01:00:01:23:64:87:b7:52:54:37:3b:87:14
eth0: IAID 37:3b:87:14
eth0: adding address fe80::904f:758c:f187:dc03
ipv6_addaddr1: Operation not supported
eth0: soliciting a DHCP lease
eth0: offered 10.0.2.15 from 10.0.2.2
eth0: leased 10.0.2.15 for 86400 seconds
eth0: adding route to 10.0.2.0/24
eth0: adding default route via 10.0.2.2
forked to background, child pid 1520
[root@alarmpi alarm]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        ether 52:54:37:3b:87:14  txqueuelen 1000  (Ethernet)
        RX packets 12  bytes 3024 (2.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17  bytes 2309 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 40  bytes 3160 (3.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 40  bytes 3160 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@alarmpi alarm]# ping www.baidu.com
PING www.a.shifen.com (61.135.169.121) 56(84) bytes of data.
 
--- www.a.shifen.com ping statistics ---
27 packets transmitted, 0 received, 100% packet loss, time 36ms

**Comment by M0Rf30** [comment]
I close this issue cause it's about credentials as in title.
