### ISSUE TITLE
[FAILED] Please specify a size in GB

### ISSUE THREAD

**Issue by agocorona** [M0Rf30/simonpi#8]
$ docker run -ti --privileged -v /dev:/dev -v ~/.simonpi:/root/.simonpi m0rf30/simonpi s
imonpi rpi-X -s Y
[ WARN ] rpi-X/boot folder is present
[ WARN ] rpi-X/root folder is present
[FAILED] Please specify a size in GB

**Comment by M0Rf30** [comment]
as you can see by your command Y stand for a size in GB and X stands for the RPI model (1 2 3)
as example 
```
simonpi rpi-3 -s 5
```

**Comment by agocorona** [comment]
Thanks!
